/**
 * This class is generated by jOOQ
 */
package com.personal.jooq.skeleton.jooq.generator;


import com.personal.jooq.skeleton.jooq.generator.tables.Author;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = com.personal.jooq.skeleton.jooq.generator.tables.Author.AUTHOR;
}
